name: 04 - Using Actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Printing Folders
              run: |
                echo ' The files / folders in the current directory are:'  
                ls -la